# services:
#   database:
#     image: "postgres:latest"
#     container_name: dc_welbex_db
#     expose:
#       - "5432"
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: backend_db
#     restart: always
#   api-service:
#     build: .
#     container_name: dc_welbex_api
#     ports:
#       - "8000:5000"
#     depends_on:
#       - database
#     restart: always

version: '2.2'

services:
  backend:
    build: budget_backend/
    ports:
      - 5000:5000
  client:
    build: budget_client/
    ports:
      - 3000:3000
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 15432:15432
    environment:
      - CUBEJS_DEV_MODE=true
    volumes:
      - .:/cube/conf