const express = require('express');
const router = express.Router();
const authorizedRouter = require('./authorized/authorizedRouter');
const freeRouter = require('./free/freeRouter');
/**
 * @openapi
 * tags:
 *   - name: '/auth'
 *     description: Auth routes
 *   - name: '/blog-post'
 *     description: Post routes
 */
/**
 * @openapi
 * components:
 *   schemas:
 *     User:
 *       type: object
 *       required:
 *         - email
 *         - password
 *       properties:
 *         id:
 *           type: integer
 *           description: Autogenerated user id
 *         email:
 *           type: string
 *           description: User email address
 *         password:
 *           type: string
 *           description: User password
 *         role:
 *           type: string
 *           description: User role
 *         createdAt:
 *           type: string
 *           description: User creation date
 *         updatedAt:
 *           type: string
 *           description: User update date
 *       example:
 *         id: 1
 *         email: test@example.com
 *         password: somestringforpassword
 *         role: admin
 *         createdAt: 2023-05-31T16:07:50.766Z
 *         updatedAt: 2023-05-31T16:07:50.766Z
 *     BlogPost:
 *       type: object
 *       required:
 *         - title
 *         - text
 *       properties:
 *         id:
 *           type: integer
 *           description: Autogenerated blog post id
 *         title:
 *           type: string
 *           description: Blog post title
 *         text:
 *           type: string
 *           description: Blog post text
 *         UserId:
 *           type: integer
 *           description: Author user id
 *         media:
 *           type: string
 *           description: Blog post`s media
 *         createdAt:
 *           type: string
 *           description: Blog post creation date
 *         updatedAt:
 *           type: string
 *           description: Blog post update date
 *         User:
 *           $ref: "#/components/schemas/User"
 *       example:
 *         id: 1
 *         title: Adventures expects!
 *         text: Lorem ipsum dolor sit am
 *         UserId: 3
 *         media: upload/jio3gh5y3igvc
 *         createdAt: 2023-05-31T16:07:50.766Z
 *         updatedAt: 2023-05-31T16:07:50.766Z
 *     ApiError:
 *       type: object
 *       properties:
 *         response: 
 *           type: string
 *           description: Custom api error text
 *   securitySchemes:
 *     BearerAuth:
 *        type: http
 *        scheme: bearer
 *        bearerFormat: JWT
 */
router.use(freeRouter);
router.use(authorizedRouter);

module.exports = router;
